Application UI
DVT-Launchpad-Web-Cadets/Musa-React-Manga-Project pull request #1
Opened 2024-03-15 18:53 UTC by Musa-Mabasa

I created the full UI for the application. I will add state management for api calls and application state in another branch.

2024-03-16 21:10 UTC, Hugovs2000 requested changes
Just a few styling suggestions that would make your design more responsive. Other than that, all good.

2024-03-16 21:10 UTC, Hugovs2000 commented on .gitignore
You should also include `dist` in the .gitignore

2024-03-16 21:10 UTC, Hugovs2000 commented on src/features/comicReader/Reader.tsx
> +    <div className="h-full w-full flex flex-col">
Dont know if you were aiming for responsiveness yet, but I realised you app is not yet capable of handling desktop view. However, I will suggest changes none the less. Maybe do `md:max-w-xl` so that the comic does not fill the screen in desktop view

2024-03-16 21:10 UTC, Hugovs2000 commented on src/features/homeFeature/components/CardsCaraousel.tsx
> +    <div className="carousel carousel-center max-w-md p-4 space-x-4 h-80 flex gap-2">
Add `md:min-w-full`

2024-03-16 21:10 UTC, Hugovs2000 commented on src/features/homeFeature/components/MangaCard.tsx
> +        className="w-full h-5/6 object-cover object-top rounded-2xl"
Rather do `w-auto h-52 rounded-2xl`. Some of you're images still appear bigger than others. This prevents that from happening. They will have varying widths though.

2024-03-16 21:10 UTC, Hugovs2000 commented on src/features/homeFeature/components/MangaCard.tsx
> +        <p className="truncate">
Alternative to this: ` <p className="line-clamp-1 hover:line-clamp-none">` when hovering over you can see the full title

2024-03-16 21:10 UTC, Hugovs2000 commented on src/features/homeFeature/components/TopSlider.tsx
> +            </div>
this div can also be made into a component then you can rather do:
```
 {topSliderManga?.slice(0, 10).map((manga) => (
<NameofComponent />
))}
```

Less clutter inside the loop

2024-03-16 21:10 UTC, Hugovs2000 commented on src/sharedComponents/backButton.tsx
Note that the file is stilled named backButton.tsx while in your import you are looking for BackButton.tsx

2024-03-16 21:10 UTC, Hugovs2000 commented on src/features/mangaViewer/components/TopHeader.tsx
> +            className=" w-full h-full object-cover rounded-2xl shadow-2xl"
Rather do: `className=" w-auto h-full md:h-2/5  rounded-2xl shadow-2xl"`

2024-03-16 21:10 UTC, Hugovs2000 commented on src/features/mangaViewer/components/TopHeader.tsx
> +        <div className="w-auto flex-1 object-cover object-top">
Add: `md:max-w-fit`

2024-03-17 10:21 UTC, Musa-Mabasa commented on src/features/comicReader/Reader.tsx
> +    <div className="h-full w-full flex flex-col">
Yes, I haven't handled responsiveness yet.

2024-03-17 10:23 UTC, Musa-Mabasa commented on src/sharedComponents/backButton.tsx
That's actually weird, I changed this file's name but somehow it didn't keep the change, thank you.

2024-03-17 10:26 UTC, Musa-Mabasa commented on .gitignore
Ahh, yes. Thank you.

2024-03-17 10:28 UTC, Musa-Mabasa commented on src/features/homeFeature/components/CardsCaraousel.tsx
> +    <div className="carousel carousel-center max-w-md p-4 space-x-4 h-80 flex gap-2">
NB: Responsiveness will come later

2024-03-17 10:28 UTC, Musa-Mabasa commented on src/features/homeFeature/components/MangaCard.tsx
> +        <p className="truncate">
Noted

2024-03-17 10:37 UTC, Musa-Mabasa commented on src/features/homeFeature/components/MangaCard.tsx
> +        className="w-full h-5/6 object-cover object-top rounded-2xl"
My issue with this is that some images appear squeezed or stretched, which can sometimes be visually unappealing. Unless I maybe misunderstood.

2024-03-17 10:39 UTC, Musa-Mabasa commented on src/features/homeFeature/components/MangaCard.tsx
> +        <p className="truncate">
Very helpful, thank you 🧠

2024-03-17 10:39 UTC, Musa-Mabasa commented on src/features/mangaViewer/components/TopHeader.tsx
> +        <div className="w-auto flex-1 object-cover object-top">
noted

2024-03-17 10:58 UTC, Musa-Mabasa commented
> Just a few styling suggestions that would make your design more responsive. Other than that, all good.

The suggested changes were made.

2024-03-17 11:00 UTC, merged